### PR TITLE
Docker support

### PR DESCRIPTION
**Pull request by reesericci**
I built a dockerfile so this can be used in container environments. This is in direct response to issue #1.

-reese

### CODE REVIEW

**Comment by reesericci** [comment]
@essej @sonosaurus

**Comment by reesericci** [comment]
closes #1

**Comment by reesericci** [comment]
closes #1

**Comment by topjor** [comment]
I would suggest you separate the build process (including deps) into a different (named) image then copy it over to the final image.

**Comment by reesericci** [comment]
Feel free to do that - I haven't worked on this in a long time.

**Comment by davemenkehorst** [comment]
I cannot find the docker file in the github image. How can i use the server with docker?

**Comment by luzpaz** [comment]
Any progress here ?

**Comment by topjor** [comment]
> Any progress here ?

I opened a new PR with my feedback implemented and updated the base image.
You can just download the Dockerfile from the PR, build the container and use it if you want  
check the readme additions for instructions. tough it is nothing special.

**Comment by reesericci** [comment]
Closing this in favor of #10

**Pull request closed without merging**
